/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDentist,
    EntDentistFromJSON,
    EntDentistFromJSONTyped,
    EntDentistToJSON,
    EntEmployee,
    EntEmployeeFromJSON,
    EntEmployeeFromJSONTyped,
    EntEmployeeToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntPillorderItem,
    EntPillorderItemFromJSON,
    EntPillorderItemFromJSONTyped,
    EntPillorderItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPillorderEdges
 */
export interface EntPillorderEdges {
    /**
     * 
     * @type {EntDentist}
     * @memberof EntPillorderEdges
     */
    dentist?: EntDentist;
    /**
     * 
     * @type {EntEmployee}
     * @memberof EntPillorderEdges
     */
    employee?: EntEmployee;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntPillorderEdges
     */
    patient?: EntPatient;
    /**
     * 
     * @type {EntPillorderItem}
     * @memberof EntPillorderEdges
     */
    pillorderitem?: EntPillorderItem;
}

export function EntPillorderEdgesFromJSON(json: any): EntPillorderEdges {
    return EntPillorderEdgesFromJSONTyped(json, false);
}

export function EntPillorderEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPillorderEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dentist': !exists(json, 'Dentist') ? undefined : EntDentistFromJSON(json['Dentist']),
        'employee': !exists(json, 'Employee') ? undefined : EntEmployeeFromJSON(json['Employee']),
        'patient': !exists(json, 'Patient') ? undefined : EntPatientFromJSON(json['Patient']),
        'pillorderitem': !exists(json, 'Pillorderitem') ? undefined : EntPillorderItemFromJSON(json['Pillorderitem']),
    };
}

export function EntPillorderEdgesToJSON(value?: EntPillorderEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dentist': EntDentistToJSON(value.dentist),
        'employee': EntEmployeeToJSON(value.employee),
        'patient': EntPatientToJSON(value.patient),
        'pillorderitem': EntPillorderItemToJSON(value.pillorderitem),
    };
}


