/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPillorderItemEdges,
    EntPillorderItemEdgesFromJSON,
    EntPillorderItemEdgesFromJSONTyped,
    EntPillorderItemEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPillorderItem
 */
export interface EntPillorderItem {
    /**
     * PillorderItemName holds the value of the "PillorderItem_name" field.
     * @type {string}
     * @memberof EntPillorderItem
     */
    pillorderItemName?: string;
    /**
     * 
     * @type {EntPillorderItemEdges}
     * @memberof EntPillorderItem
     */
    edges?: EntPillorderItemEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPillorderItem
     */
    id?: number;
}

export function EntPillorderItemFromJSON(json: any): EntPillorderItem {
    return EntPillorderItemFromJSONTyped(json, false);
}

export function EntPillorderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPillorderItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pillorderItemName': !exists(json, 'PillorderItem_name') ? undefined : json['PillorderItem_name'],
        'edges': !exists(json, 'edges') ? undefined : EntPillorderItemEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPillorderItemToJSON(value?: EntPillorderItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PillorderItem_name': value.pillorderItemName,
        'edges': EntPillorderItemEdgesToJSON(value.edges),
        'id': value.id,
    };
}


