// Code generated by entc, DO NOT EDIT.

package dentist

const (
	// Label holds the string label denoting the dentist type in the database.
	Label = "dentist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDentistName holds the string denoting the dentist_name field in the database.
	FieldDentistName = "dentist_name"

	// EdgePillorders holds the string denoting the pillorders edge name in mutations.
	EdgePillorders = "pillorders"

	// Table holds the table name of the dentist in the database.
	Table = "dentists"
	// PillordersTable is the table the holds the pillorders relation/edge.
	PillordersTable = "pillorders"
	// PillordersInverseTable is the table name for the Pillorder entity.
	// It exists in this package in order to avoid circular dependency with the "pillorder" package.
	PillordersInverseTable = "pillorders"
	// PillordersColumn is the table column denoting the pillorders relation/edge.
	PillordersColumn = "dentist_id"
)

// Columns holds all SQL columns for dentist fields.
var Columns = []string{
	FieldID,
	FieldDentistName,
}

var (
	// DentistNameValidator is a validator for the "Dentist_name" field. It is called by the builders before save.
	DentistNameValidator func(string) error
)
