// Code generated by entc, DO NOT EDIT.

package employee

const (
	// Label holds the string label denoting the employee type in the database.
	Label = "employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmployeeName holds the string denoting the employee_name field in the database.
	FieldEmployeeName = "employee_name"
	// FieldEmployeeEmail holds the string denoting the employee_email field in the database.
	FieldEmployeeEmail = "employee_email"
	// FieldEmployeePassword holds the string denoting the employee_password field in the database.
	FieldEmployeePassword = "employee_password"

	// EdgePillorders holds the string denoting the pillorders edge name in mutations.
	EdgePillorders = "pillorders"

	// Table holds the table name of the employee in the database.
	Table = "employees"
	// PillordersTable is the table the holds the pillorders relation/edge.
	PillordersTable = "pillorders"
	// PillordersInverseTable is the table name for the Pillorder entity.
	// It exists in this package in order to avoid circular dependency with the "pillorder" package.
	PillordersInverseTable = "pillorders"
	// PillordersColumn is the table column denoting the pillorders relation/edge.
	PillordersColumn = "employee_id"
)

// Columns holds all SQL columns for employee fields.
var Columns = []string{
	FieldID,
	FieldEmployeeName,
	FieldEmployeeEmail,
	FieldEmployeePassword,
}

var (
	// EmployeeNameValidator is a validator for the "employee_name" field. It is called by the builders before save.
	EmployeeNameValidator func(string) error
	// EmployeeEmailValidator is a validator for the "employee_email" field. It is called by the builders before save.
	EmployeeEmailValidator func(string) error
	// EmployeePasswordValidator is a validator for the "employee_password" field. It is called by the builders before save.
	EmployeePasswordValidator func(string) error
)
