// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/patiwatpanda/app/ent/pillorder"
	"github.com/patiwatpanda/app/ent/pillorderitem"
	"github.com/patiwatpanda/app/ent/predicate"
)

// PillorderItemQuery is the builder for querying PillorderItem entities.
type PillorderItemQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.PillorderItem
	// eager-loading edges.
	withPillorders *PillorderQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (piq *PillorderItemQuery) Where(ps ...predicate.PillorderItem) *PillorderItemQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit adds a limit step to the query.
func (piq *PillorderItemQuery) Limit(limit int) *PillorderItemQuery {
	piq.limit = &limit
	return piq
}

// Offset adds an offset step to the query.
func (piq *PillorderItemQuery) Offset(offset int) *PillorderItemQuery {
	piq.offset = &offset
	return piq
}

// Order adds an order step to the query.
func (piq *PillorderItemQuery) Order(o ...OrderFunc) *PillorderItemQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// QueryPillorders chains the current query on the pillorders edge.
func (piq *PillorderItemQuery) QueryPillorders() *PillorderQuery {
	query := &PillorderQuery{config: piq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pillorderitem.Table, pillorderitem.FieldID, piq.sqlQuery()),
			sqlgraph.To(pillorder.Table, pillorder.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pillorderitem.PillordersTable, pillorderitem.PillordersColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PillorderItem entity in the query. Returns *NotFoundError when no pillorderitem was found.
func (piq *PillorderItemQuery) First(ctx context.Context) (*PillorderItem, error) {
	pis, err := piq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(pis) == 0 {
		return nil, &NotFoundError{pillorderitem.Label}
	}
	return pis[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *PillorderItemQuery) FirstX(ctx context.Context) *PillorderItem {
	pi, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return pi
}

// FirstID returns the first PillorderItem id in the query. Returns *NotFoundError when no id was found.
func (piq *PillorderItemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pillorderitem.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (piq *PillorderItemQuery) FirstXID(ctx context.Context) int {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only PillorderItem entity in the query, returns an error if not exactly one entity was returned.
func (piq *PillorderItemQuery) Only(ctx context.Context) (*PillorderItem, error) {
	pis, err := piq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(pis) {
	case 1:
		return pis[0], nil
	case 0:
		return nil, &NotFoundError{pillorderitem.Label}
	default:
		return nil, &NotSingularError{pillorderitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *PillorderItemQuery) OnlyX(ctx context.Context) *PillorderItem {
	pi, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return pi
}

// OnlyID returns the only PillorderItem id in the query, returns an error if not exactly one id was returned.
func (piq *PillorderItemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pillorderitem.Label}
	default:
		err = &NotSingularError{pillorderitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *PillorderItemQuery) OnlyIDX(ctx context.Context) int {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PillorderItems.
func (piq *PillorderItemQuery) All(ctx context.Context) ([]*PillorderItem, error) {
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return piq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (piq *PillorderItemQuery) AllX(ctx context.Context) []*PillorderItem {
	pis, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return pis
}

// IDs executes the query and returns a list of PillorderItem ids.
func (piq *PillorderItemQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := piq.Select(pillorderitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *PillorderItemQuery) IDsX(ctx context.Context) []int {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *PillorderItemQuery) Count(ctx context.Context) (int, error) {
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return piq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (piq *PillorderItemQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *PillorderItemQuery) Exist(ctx context.Context) (bool, error) {
	if err := piq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return piq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *PillorderItemQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *PillorderItemQuery) Clone() *PillorderItemQuery {
	return &PillorderItemQuery{
		config:     piq.config,
		limit:      piq.limit,
		offset:     piq.offset,
		order:      append([]OrderFunc{}, piq.order...),
		unique:     append([]string{}, piq.unique...),
		predicates: append([]predicate.PillorderItem{}, piq.predicates...),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

//  WithPillorders tells the query-builder to eager-loads the nodes that are connected to
// the "pillorders" edge. The optional arguments used to configure the query builder of the edge.
func (piq *PillorderItemQuery) WithPillorders(opts ...func(*PillorderQuery)) *PillorderItemQuery {
	query := &PillorderQuery{config: piq.config}
	for _, opt := range opts {
		opt(query)
	}
	piq.withPillorders = query
	return piq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PillorderItemName string `json:"PillorderItem_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PillorderItem.Query().
//		GroupBy(pillorderitem.FieldPillorderItemName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (piq *PillorderItemQuery) GroupBy(field string, fields ...string) *PillorderItemGroupBy {
	group := &PillorderItemGroupBy{config: piq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return piq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		PillorderItemName string `json:"PillorderItem_name,omitempty"`
//	}
//
//	client.PillorderItem.Query().
//		Select(pillorderitem.FieldPillorderItemName).
//		Scan(ctx, &v)
//
func (piq *PillorderItemQuery) Select(field string, fields ...string) *PillorderItemSelect {
	selector := &PillorderItemSelect{config: piq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return piq.sqlQuery(), nil
	}
	return selector
}

func (piq *PillorderItemQuery) prepareQuery(ctx context.Context) error {
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *PillorderItemQuery) sqlAll(ctx context.Context) ([]*PillorderItem, error) {
	var (
		nodes       = []*PillorderItem{}
		_spec       = piq.querySpec()
		loadedTypes = [1]bool{
			piq.withPillorders != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &PillorderItem{config: piq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := piq.withPillorders; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*PillorderItem)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.Pillorder(func(s *sql.Selector) {
			s.Where(sql.InValues(pillorderitem.PillordersColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.pillorderitem_id
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "pillorderitem_id" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "pillorderitem_id" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Pillorders = append(node.Edges.Pillorders, n)
		}
	}

	return nodes, nil
}

func (piq *PillorderItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *PillorderItemQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := piq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (piq *PillorderItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pillorderitem.Table,
			Columns: pillorderitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pillorderitem.FieldID,
			},
		},
		From:   piq.sql,
		Unique: true,
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *PillorderItemQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(pillorderitem.Table)
	selector := builder.Select(t1.Columns(pillorderitem.Columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(pillorderitem.Columns...)...)
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PillorderItemGroupBy is the builder for group-by PillorderItem entities.
type PillorderItemGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *PillorderItemGroupBy) Aggregate(fns ...AggregateFunc) *PillorderItemGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the group-by query and scan the result into the given value.
func (pigb *PillorderItemGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pigb.path(ctx)
	if err != nil {
		return err
	}
	pigb.sql = query
	return pigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pigb *PillorderItemGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (pigb *PillorderItemGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pigb.fields) > 1 {
		return nil, errors.New("ent: PillorderItemGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pigb *PillorderItemGroupBy) StringsX(ctx context.Context) []string {
	v, err := pigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (pigb *PillorderItemGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pigb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pillorderitem.Label}
	default:
		err = fmt.Errorf("ent: PillorderItemGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pigb *PillorderItemGroupBy) StringX(ctx context.Context) string {
	v, err := pigb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (pigb *PillorderItemGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pigb.fields) > 1 {
		return nil, errors.New("ent: PillorderItemGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pigb *PillorderItemGroupBy) IntsX(ctx context.Context) []int {
	v, err := pigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (pigb *PillorderItemGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pigb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pillorderitem.Label}
	default:
		err = fmt.Errorf("ent: PillorderItemGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pigb *PillorderItemGroupBy) IntX(ctx context.Context) int {
	v, err := pigb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (pigb *PillorderItemGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pigb.fields) > 1 {
		return nil, errors.New("ent: PillorderItemGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pigb *PillorderItemGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (pigb *PillorderItemGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pigb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pillorderitem.Label}
	default:
		err = fmt.Errorf("ent: PillorderItemGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pigb *PillorderItemGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pigb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (pigb *PillorderItemGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pigb.fields) > 1 {
		return nil, errors.New("ent: PillorderItemGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pigb *PillorderItemGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (pigb *PillorderItemGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pigb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pillorderitem.Label}
	default:
		err = fmt.Errorf("ent: PillorderItemGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pigb *PillorderItemGroupBy) BoolX(ctx context.Context) bool {
	v, err := pigb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pigb *PillorderItemGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pigb.sqlQuery().Query()
	if err := pigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pigb *PillorderItemGroupBy) sqlQuery() *sql.Selector {
	selector := pigb.sql
	columns := make([]string, 0, len(pigb.fields)+len(pigb.fns))
	columns = append(columns, pigb.fields...)
	for _, fn := range pigb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(pigb.fields...)
}

// PillorderItemSelect is the builder for select fields of PillorderItem entities.
type PillorderItemSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (pis *PillorderItemSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := pis.path(ctx)
	if err != nil {
		return err
	}
	pis.sql = query
	return pis.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pis *PillorderItemSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pis.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (pis *PillorderItemSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pis.fields) > 1 {
		return nil, errors.New("ent: PillorderItemSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pis *PillorderItemSelect) StringsX(ctx context.Context) []string {
	v, err := pis.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (pis *PillorderItemSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pis.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pillorderitem.Label}
	default:
		err = fmt.Errorf("ent: PillorderItemSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pis *PillorderItemSelect) StringX(ctx context.Context) string {
	v, err := pis.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (pis *PillorderItemSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pis.fields) > 1 {
		return nil, errors.New("ent: PillorderItemSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pis *PillorderItemSelect) IntsX(ctx context.Context) []int {
	v, err := pis.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (pis *PillorderItemSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pis.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pillorderitem.Label}
	default:
		err = fmt.Errorf("ent: PillorderItemSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pis *PillorderItemSelect) IntX(ctx context.Context) int {
	v, err := pis.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (pis *PillorderItemSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pis.fields) > 1 {
		return nil, errors.New("ent: PillorderItemSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pis *PillorderItemSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pis.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (pis *PillorderItemSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pis.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pillorderitem.Label}
	default:
		err = fmt.Errorf("ent: PillorderItemSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pis *PillorderItemSelect) Float64X(ctx context.Context) float64 {
	v, err := pis.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (pis *PillorderItemSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pis.fields) > 1 {
		return nil, errors.New("ent: PillorderItemSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pis *PillorderItemSelect) BoolsX(ctx context.Context) []bool {
	v, err := pis.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (pis *PillorderItemSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pis.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{pillorderitem.Label}
	default:
		err = fmt.Errorf("ent: PillorderItemSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pis *PillorderItemSelect) BoolX(ctx context.Context) bool {
	v, err := pis.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pis *PillorderItemSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pis.sqlQuery().Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pis *PillorderItemSelect) sqlQuery() sql.Querier {
	selector := pis.sql
	selector.Select(selector.Columns(pis.fields...)...)
	return selector
}
