// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/patiwatpanda/app/ent/pillorderitem"
	"github.com/patiwatpanda/app/ent/predicate"
)

// PillorderItemDelete is the builder for deleting a PillorderItem entity.
type PillorderItemDelete struct {
	config
	hooks      []Hook
	mutation   *PillorderItemMutation
	predicates []predicate.PillorderItem
}

// Where adds a new predicate to the delete builder.
func (pid *PillorderItemDelete) Where(ps ...predicate.PillorderItem) *PillorderItemDelete {
	pid.predicates = append(pid.predicates, ps...)
	return pid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pid *PillorderItemDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pid.hooks) == 0 {
		affected, err = pid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PillorderItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pid.mutation = mutation
			affected, err = pid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pid.hooks) - 1; i >= 0; i-- {
			mut = pid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pid *PillorderItemDelete) ExecX(ctx context.Context) int {
	n, err := pid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pid *PillorderItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: pillorderitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pillorderitem.FieldID,
			},
		},
	}
	if ps := pid.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pid.driver, _spec)
}

// PillorderItemDeleteOne is the builder for deleting a single PillorderItem entity.
type PillorderItemDeleteOne struct {
	pid *PillorderItemDelete
}

// Exec executes the deletion query.
func (pido *PillorderItemDeleteOne) Exec(ctx context.Context) error {
	n, err := pido.pid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pillorderitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pido *PillorderItemDeleteOne) ExecX(ctx context.Context) {
	pido.pid.ExecX(ctx)
}
