// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/patiwatpanda/app/ent/pillorder"
	"github.com/patiwatpanda/app/ent/pillorderitem"
)

// PillorderItemCreate is the builder for creating a PillorderItem entity.
type PillorderItemCreate struct {
	config
	mutation *PillorderItemMutation
	hooks    []Hook
}

// SetPillorderItemName sets the PillorderItem_name field.
func (pic *PillorderItemCreate) SetPillorderItemName(s string) *PillorderItemCreate {
	pic.mutation.SetPillorderItemName(s)
	return pic
}

// AddPillorderIDs adds the pillorders edge to Pillorder by ids.
func (pic *PillorderItemCreate) AddPillorderIDs(ids ...int) *PillorderItemCreate {
	pic.mutation.AddPillorderIDs(ids...)
	return pic
}

// AddPillorders adds the pillorders edges to Pillorder.
func (pic *PillorderItemCreate) AddPillorders(p ...*Pillorder) *PillorderItemCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pic.AddPillorderIDs(ids...)
}

// Mutation returns the PillorderItemMutation object of the builder.
func (pic *PillorderItemCreate) Mutation() *PillorderItemMutation {
	return pic.mutation
}

// Save creates the PillorderItem in the database.
func (pic *PillorderItemCreate) Save(ctx context.Context) (*PillorderItem, error) {
	if _, ok := pic.mutation.PillorderItemName(); !ok {
		return nil, &ValidationError{Name: "PillorderItem_name", err: errors.New("ent: missing required field \"PillorderItem_name\"")}
	}
	if v, ok := pic.mutation.PillorderItemName(); ok {
		if err := pillorderitem.PillorderItemNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "PillorderItem_name", err: fmt.Errorf("ent: validator failed for field \"PillorderItem_name\": %w", err)}
		}
	}
	var (
		err  error
		node *PillorderItem
	)
	if len(pic.hooks) == 0 {
		node, err = pic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PillorderItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pic.mutation = mutation
			node, err = pic.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pic.hooks) - 1; i >= 0; i-- {
			mut = pic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pic *PillorderItemCreate) SaveX(ctx context.Context) *PillorderItem {
	v, err := pic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pic *PillorderItemCreate) sqlSave(ctx context.Context) (*PillorderItem, error) {
	pi, _spec := pic.createSpec()
	if err := sqlgraph.CreateNode(ctx, pic.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pi.ID = int(id)
	return pi, nil
}

func (pic *PillorderItemCreate) createSpec() (*PillorderItem, *sqlgraph.CreateSpec) {
	var (
		pi    = &PillorderItem{config: pic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: pillorderitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pillorderitem.FieldID,
			},
		}
	)
	if value, ok := pic.mutation.PillorderItemName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pillorderitem.FieldPillorderItemName,
		})
		pi.PillorderItemName = value
	}
	if nodes := pic.mutation.PillordersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pillorderitem.PillordersTable,
			Columns: []string{pillorderitem.PillordersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pillorder.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pi, _spec
}
