// Code generated by entc, DO NOT EDIT.

package pillorderitem

const (
	// Label holds the string label denoting the pillorderitem type in the database.
	Label = "pillorder_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPillorderItemName holds the string denoting the pillorderitem_name field in the database.
	FieldPillorderItemName = "pillorder_item_name"

	// EdgePillorders holds the string denoting the pillorders edge name in mutations.
	EdgePillorders = "pillorders"

	// Table holds the table name of the pillorderitem in the database.
	Table = "pillorder_items"
	// PillordersTable is the table the holds the pillorders relation/edge.
	PillordersTable = "pillorders"
	// PillordersInverseTable is the table name for the Pillorder entity.
	// It exists in this package in order to avoid circular dependency with the "pillorder" package.
	PillordersInverseTable = "pillorders"
	// PillordersColumn is the table column denoting the pillorders relation/edge.
	PillordersColumn = "pillorderitem_id"
)

// Columns holds all SQL columns for pillorderitem fields.
var Columns = []string{
	FieldID,
	FieldPillorderItemName,
}

var (
	// PillorderItemNameValidator is a validator for the "PillorderItem_name" field. It is called by the builders before save.
	PillorderItemNameValidator func(string) error
)
