// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// DentistsColumns holds the columns for the "dentists" table.
	DentistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "dentist_name", Type: field.TypeString},
	}
	// DentistsTable holds the schema information for the "dentists" table.
	DentistsTable = &schema.Table{
		Name:        "dentists",
		Columns:     DentistsColumns,
		PrimaryKey:  []*schema.Column{DentistsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// EmployeesColumns holds the columns for the "employees" table.
	EmployeesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "employee_name", Type: field.TypeString},
		{Name: "employee_email", Type: field.TypeString},
		{Name: "employee_password", Type: field.TypeString},
	}
	// EmployeesTable holds the schema information for the "employees" table.
	EmployeesTable = &schema.Table{
		Name:        "employees",
		Columns:     EmployeesColumns,
		PrimaryKey:  []*schema.Column{EmployeesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PatientsColumns holds the columns for the "patients" table.
	PatientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "patient_name", Type: field.TypeString},
		{Name: "patient_age", Type: field.TypeInt},
	}
	// PatientsTable holds the schema information for the "patients" table.
	PatientsTable = &schema.Table{
		Name:        "patients",
		Columns:     PatientsColumns,
		PrimaryKey:  []*schema.Column{PatientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PillordersColumns holds the columns for the "pillorders" table.
	PillordersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "pillorder_name_id", Type: field.TypeString},
		{Name: "pillorder_date", Type: field.TypeTime},
		{Name: "dentist_id", Type: field.TypeInt, Nullable: true},
		{Name: "employee_id", Type: field.TypeInt, Nullable: true},
		{Name: "patient_id", Type: field.TypeInt, Nullable: true},
		{Name: "pillorderitem_id", Type: field.TypeInt, Nullable: true},
	}
	// PillordersTable holds the schema information for the "pillorders" table.
	PillordersTable = &schema.Table{
		Name:       "pillorders",
		Columns:    PillordersColumns,
		PrimaryKey: []*schema.Column{PillordersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "pillorders_dentists_pillorders",
				Columns: []*schema.Column{PillordersColumns[3]},

				RefColumns: []*schema.Column{DentistsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "pillorders_employees_pillorders",
				Columns: []*schema.Column{PillordersColumns[4]},

				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "pillorders_patients_pillorders",
				Columns: []*schema.Column{PillordersColumns[5]},

				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "pillorders_pillorder_items_pillorders",
				Columns: []*schema.Column{PillordersColumns[6]},

				RefColumns: []*schema.Column{PillorderItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PillorderItemsColumns holds the columns for the "pillorder_items" table.
	PillorderItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "pillorder_item_name", Type: field.TypeString},
	}
	// PillorderItemsTable holds the schema information for the "pillorder_items" table.
	PillorderItemsTable = &schema.Table{
		Name:        "pillorder_items",
		Columns:     PillorderItemsColumns,
		PrimaryKey:  []*schema.Column{PillorderItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DentistsTable,
		EmployeesTable,
		PatientsTable,
		PillordersTable,
		PillorderItemsTable,
	}
)

func init() {
	PillordersTable.ForeignKeys[0].RefTable = DentistsTable
	PillordersTable.ForeignKeys[1].RefTable = EmployeesTable
	PillordersTable.ForeignKeys[2].RefTable = PatientsTable
	PillordersTable.ForeignKeys[3].RefTable = PillorderItemsTable
}
